export declare const CELL_M: 64;
export declare const CELL_N: Readonly<{ high: 256; low: 128 }>;
export declare const SDF: Readonly<{ minM: number; rangeM: number }>;
export declare const RUT: Readonly<{ minM: number; rangeM: number; sentinel: 255; evalMaxM: number; centreM: number; profileHalfM: number;
	depthM: number; wanderM: number; wanderFreq: number }>;
export declare const BERM: Readonly<{ dMin: number; dMax: number; heightM: number }>;
export declare const BLEND: Readonly<{ lambda: number; delta: number; ramp: number; hScale: readonly number[]; hBias: readonly number[] }>;
export declare const EDGE_BREAKUP: Readonly<{ bandM: number; amp: number; freqs: readonly number[]; weights: readonly number[] }>;
export declare const ANTI_TILING: Readonly<{ cos: number; sin: number; offset: readonly [number, number]; maskPeriodM: number;
	maskEdges: readonly [number, number]; heightGain: number }>;
export declare const MACRO: Readonly<{ periodsM: readonly number[]; weights: readonly number[]; value: readonly [number, number];
	cool: readonly [number, number, number]; warm: readonly [number, number, number]; hueEdges: readonly [number, number] }>;
export type TerrainTier = 0 | 1 | 2;
export declare const FAR_FADE: Readonly<Record<TerrainTier, readonly [number, number]>>;
export declare const TIER_PRESETS: Readonly<Record<"low" | "medium" | "high" | "ultra", TerrainTier>>;
export declare const TIER_ANISOTROPY: Readonly<Record<TerrainTier, number>>;
export declare const LAYER_IDS: readonly ["L0", "L1", "L2", "L3"];
export declare const BRANCH_EPS: number;
export declare const FAR_DRY_SHARE: number;
export declare const TIER0_NRO_MIN: number;
export declare const SAMPLER_BUDGET: Readonly<{ basePbr: number; limit: number; cellCustom: number; farCustom: number; genericRockCustom: number;
	heroRockCustom: number }>;
export declare function smoothstep(a: number, b: number, x: number): number;
export declare function cellUV(x: number, z: number, minX: number, minZ: number, n?: number): { u: number; v: number };
export declare function cellTexel(x: number, z: number, minX: number, minZ: number, n?: number): { col: number; row: number };
export declare function texelWorld(col: number, row: number, minX: number, minZ: number, n?: number): { x: number; z: number };
export declare function texelAtUV(u: number, v: number, n?: number): { col: number; row: number };
export declare function encodeSdf(d: number): number;
export declare function decodeSdf(byte: number): number;
export declare function encodeRut(l: number | null | undefined): number;
export declare function decodeRut(byte: number): number | null;
export declare function splatWeights(r: number, g: number, b: number): [number, number, number, number];
export declare function quantiseWeights(w: readonly number[]): number[];
export declare function heightBlend(weights: readonly number[], heights: readonly number[], opts?: {
	lambda?: number; delta?: number; ramp?: number; hScale?: readonly number[]; hBias?: readonly number[];
}): number[];
export declare function rotateUV(u: number, v: number): { u: number; v: number };
export declare function unrotateNormalXY(x: number, y: number): { x: number; y: number };
export declare function rotateNormalXY(x: number, y: number): { x: number; y: number };
export declare function antiTilingBlend(maskNoise: number, hA: number, hB: number): number;
export declare function resolveTier(preset: string | { preset: string }): TerrainTier;
export declare function farFade(distanceM: number, tier: TerrainTier): number;
export declare function rutProfile(s: number): number;
export declare function rutSlope(s: number): number;
export declare function bermProfile(d: number): number;
export declare function hash12(x: number, y: number): number;
export declare function valueNoise(x: number, y: number): number;
export declare function valueNoiseShared(x: number, y: number): number;
export declare function hashExact(ix: number, iy: number): number;
export declare function valueNoiseExact(x: number, y: number): number;
export declare function macroField(x: number, z: number): number;
export declare function antiTilingMaskField(x: number, z: number): number;
export interface DecodedPng { width: number; height: number; channels: number; data: Uint8Array }
export declare function decodePng(bytes: ArrayBuffer | Uint8Array, inflate: (data: Uint8Array) => Uint8Array | Promise<Uint8Array>): Promise<DecodedPng>;
export type CellFieldKind = "macro" | "mask";
export declare function cellFieldGrid(kind: CellFieldKind, minX: number, minZ: number, n: number): Float64Array;
export declare function bakeCellMapRGBA(png: DecodedPng, field: CellFieldKind | ((x: number, z: number) => number), minX: number, minZ: number, n?: number): Uint8Array;
export declare function memoryEstimateMiB(input: { layerSizes: readonly number[]; cellTexels: number; cells: number; compressed?: boolean;
	cellMaps?: number }): number;
export type TerrainSlot = "grass_ground" | "terrain_bluff_rock" | "terrain_cliff_rock" | "terrain_outcrop_rock" | "terrain_ground_decal";
export declare const TERRAIN_SLOTS: Readonly<Record<TerrainSlot, "cell" | "rock" | "decal">>;
export declare function terrainSlotOf(meshName: string): TerrainSlot | null;
