"""Water-edge flora kit (P1): 3 lily pad variants, lotus bud/open in pink and white, 3 reed/cattail clumps.

Recipes (seeded, parametric, LOD0-2 generated by the same recipe at lower detail):
  flora.lilypad/1  floating pads: fan disc with a notch (sinus), cupped rim, edge wave, optional curled young pad
  flora.lotus/1    petal-ring recipe: rings of curved 12-triangle petals (count, length, width, tilt, cup, curl),
                   seed pod frustum + stamen ring card, curved stem, optional floating lotus leaf; bud = closed rings
  flora.reeds/1    clump of bent vertical blade cards (several painted blades per card) + cattail stems and heads
UV0 maps into the painted atlas sm_flora_water (flora_layout.WATER). UV1 'wind' = TEXCOORD_1 for nature-motion.ts
uv2 mode: x = sway weight (0 at the water/ground, 1 at the tips), y stored as 1 - phase (exporter flips v).
Alpha-tested (cutoff 0.5) double-sided material, foliage profile. Pivot: water surface / ground contact at y = 0.
"""
from __future__ import annotations

import math

import bpy
import numpy as np

import flora_layout as FL
import np_lib as L

KIT = "flora"
ATLASES = [{"id": "sm_flora_water", "albedo_px": 1024, "data_px": 512, "orm_px": 256, "palette": None,
            "budget_class": "bush_lod0", "profile": "foliage", "painted": True,
            "material": {"alpha_clip": 0.5, "double_sided": True}}]
LAY = FL.WATER


class MB:
    """Mesh builder with per-corner UV0 and wind UV1."""

    def __init__(self):
        self.v, self.f, self.uv, self.wind = [], [], [], []

    def vert(self, p):
        self.v.append(tuple(float(x) for x in p))
        return len(self.v) - 1

    def face(self, idx, uvs, winds):
        self.f.append(list(idx))
        self.uv.extend([tuple(u) for u in uvs])
        self.wind.extend([tuple(w) for w in winds])

    def build(self, name):
        ob = L.mesh_from_arrays(name, np.array(self.v), self.f)
        me = ob.data
        if len(me.loops) != len(self.uv):
            raise ValueError('Recipe validation changed corner count; UV/wind data cannot be assigned safely')
        uv0 = me.uv_layers.new(name="UVMap")
        uv1 = me.uv_layers.new(name="wind")
        # from_pydata keeps face corner order, so loops follow self.uv order
        uv0.data.foreach_set("uv", np.array(self.uv, dtype=np.float32).ravel())
        uv1.data.foreach_set("uv", np.array(self.wind, dtype=np.float32).ravel())
        me.uv_layers.active = uv0
        L.set_smooth(ob)
        return ob


def rect_uv(name, u, v):
    """u, v in 0..1 inside the named atlas rect (v up) -> atlas UV."""
    u0, v0, du, dv = FL.uv_rect(LAY, name)
    return (u0 + du * u, v0 + dv * v)


def wind_uv(weight, phase):
    return (float(np.clip(weight, 0, 1)), float(1.0 - np.clip(phase, 0, 0.999)))


# --------------------------------------------------------------------------------------------- lily pads

def _pad(mb, cx, cy, r, rot, tex, seg, notch_deg, cup, wave, rings, phase, z0=0.004, lift=0.0, curl=0.0):
    half = math.radians(notch_deg) / 2
    c = mb.vert((cx, cy, z0 + lift))
    angs = np.linspace(half, 2 * math.pi - half, seg + 1)
    radii = [0.55, 1.0] if rings == 2 else [1.0]
    ring_idx = []
    for rf in radii:
        row = []
        for a in angs:
            rr = r * rf
            lx, ly = rr * math.cos(a), rr * math.sin(a)
            z = z0 + lift + cup * rf ** 2.2 + wave * math.sin(a * 5 + phase * 6.28) * rf ** 2
            if curl > 0:   # young pad: one side rolls up
                z += curl * max(0.0, math.cos(a - math.pi)) ** 2 * rf ** 1.5
            x = cx + lx * math.cos(rot) - ly * math.sin(rot)
            y = cy + lx * math.sin(rot) + ly * math.cos(rot)
            row.append((mb.vert((x, y, z)), (lx / r, ly / r), rf))
        ring_idx.append(row)

    def uvp(lxy):
        return rect_uv(tex, 0.5 + 0.47 * lxy[0] / 0.98 * 0.98, 0.5 + 0.47 * lxy[1])

    wc = wind_uv(0.0, phase)
    inner = ring_idx[0]
    for k in range(seg):
        a, b = inner[k], inner[k + 1]
        mb.face([c, a[0], b[0]], [uvp((0, 0)), uvp(a[1]), uvp(b[1])],
                [wc, wind_uv(0.05 * a[2], phase), wind_uv(0.05 * b[2], phase)])
    if len(ring_idx) == 2:
        outer = ring_idx[1]
        for k in range(seg):
            a, b, d, e = inner[k], inner[k + 1], outer[k + 1], outer[k]
            mb.face([a[0], e[0], d[0], b[0]], [uvp(a[1]), uvp(e[1]), uvp(d[1]), uvp(b[1])],
                    [wind_uv(0.05 * a[2], phase), wind_uv(0.08, phase), wind_uv(0.08, phase), wind_uv(0.05 * b[2], phase)])


def lilypad_lods(spec):
    P = spec["params"]
    out = {}
    for lod, seg, rings in ((0, P.get("seg", 12), 2), (1, 8, 1), (2, 6, 1)):
        mb = MB()
        for i, pd in enumerate(P["pads"]):
            _pad(mb, pd["x"], pd["y"], pd["r"], math.radians(pd["rot"]), pd["tex"], seg if not pd.get("young") else max(6, seg - 4),
                 pd.get("notch", 28.0), pd.get("cup", 0.012), pd.get("wave", 0.004), rings,
                 phase=(0.618 * (i + 1) + spec["seed"] * 0.137) % 1.0, lift=pd.get("lift", 0.0), curl=pd.get("curl", 0.0))
        out[f"lod{lod}"] = mb.build(f"{spec['id']}__lod{lod}")
    return out


# --------------------------------------------------------------------------------------------- lotus

def _hw_paint(s):
    s = min(max(s, 0.0), 1.0)
    return 0.93 * math.sin(math.pi * max(s, 1e-4) ** 0.78) ** 0.8 * (1 - 0.1 * s)


def _petal(mb, base, ang, length, width, tilt_deg, cup, curl, tex, rows, phase, z_top, twist=0.0):
    radial = np.array([math.cos(ang), math.sin(ang), 0.0])
    tang = np.array([-math.sin(ang), math.cos(ang), 0.0])
    up = np.array([0, 0, 1.0])
    ss_ = np.linspace(0, 1, rows)
    grid = []
    for s in ss_:
        t = math.radians(tilt_deg + curl * s ** 2 * 35.0)
        g = up * math.cos(t) + radial * math.sin(t)
        nrm = np.cross(tang, g)
        nrm /= np.linalg.norm(nrm)
        # centre line integrates the bending direction
        hw_geo = 1.12 * _hw_paint(0.015 + 0.97 * s) + 0.05 if 0 < s < 1 else (0.22 if s == 0 else 0.12)
        row = []
        for q in (-1.0, 0.0, 1.0):
            p = np.array(base) + g * length * s
            p = p + tang * (q * hw_geo * width * 0.5) * math.cos(twist) + nrm * (cup * width * (q * q) * hw_geo)
            u = 0.5 + 0.5 * q * hw_geo * 0.98
            v = 0.015 + 0.97 * s
            h_weight = (p[2] / max(z_top, 1e-3)) ** 1.5 * 0.35
            row.append((mb.vert(p), rect_uv(tex, u, v), wind_uv(h_weight, phase)))
        grid.append(row)
    for r in range(rows - 1):
        for c in range(2):
            a, b, d, e = grid[r][c], grid[r][c + 1], grid[r + 1][c + 1], grid[r + 1][c]
            mb.face([a[0], b[0], d[0], e[0]], [a[1], b[1], d[1], e[1]], [a[2], b[2], d[2], e[2]])


def _ring_mesh(mb, cx, cy, z, r0, r1, z1, n, tex, uv_fn, phase, z_top):
    for k in range(n):
        a0, a1 = 2 * math.pi * k / n, 2 * math.pi * (k + 1) / n
        p = [(cx + r0 * math.cos(a0), cy + r0 * math.sin(a0), z), (cx + r0 * math.cos(a1), cy + r0 * math.sin(a1), z),
             (cx + r1 * math.cos(a1), cy + r1 * math.sin(a1), z1), (cx + r1 * math.cos(a0), cy + r1 * math.sin(a0), z1)]
        idx = [mb.vert(x) for x in p]
        uvs = [uv_fn(k / n, 0), uv_fn((k + 1) / n, 0), uv_fn((k + 1) / n, 1), uv_fn(k / n, 1)]
        w = [wind_uv((x[2] / max(z_top, 1e-3)) ** 1.5 * 0.35, phase) for x in p]
        mb.face(idx, uvs, w)


def _disc(mb, cx, cy, z, r, n, tex, phase, z_top, flip=False):
    c = mb.vert((cx, cy, z))
    ring = [mb.vert((cx + r * math.cos(2 * math.pi * k / n), cy + r * math.sin(2 * math.pi * k / n), z)) for k in range(n)]
    for k in range(n):
        a0, a1 = 2 * math.pi * k / n, 2 * math.pi * (k + 1) / n
        uv = [rect_uv(tex, 0.5, 0.5), rect_uv(tex, 0.5 + 0.46 * math.cos(a0), 0.5 + 0.46 * math.sin(a0)),
              rect_uv(tex, 0.5 + 0.46 * math.cos(a1), 0.5 + 0.46 * math.sin(a1))]
        w = [wind_uv((z / max(z_top, 1e-3)) ** 1.5 * 0.35, phase)] * 3
        idx = [c, ring[k], ring[(k + 1) % n]]
        if flip:
            idx, uv = idx[::-1], uv[::-1]
        mb.face(idx, uv, w)


def _stem(mb, base, top, radius, sides, segs, tex, phase, z_top, bow=0.02):
    base, top = np.array(base, float), np.array(top, float)
    axis = top - base
    side = np.cross(axis, [0, 0, 1.0]) if abs(axis[2]) < 0.99 * np.linalg.norm(axis) else np.array([1.0, 0, 0])
    side /= np.linalg.norm(side) + 1e-9
    rings = []
    for j in range(segs + 1):
        s = j / segs
        c = base + axis * s + side * bow * math.sin(math.pi * s)
        a = axis / np.linalg.norm(axis)
        e1 = np.cross(a, [0, 1.0, 0]) if abs(a[1]) < 0.9 else np.cross(a, [1.0, 0, 0])
        e1 /= np.linalg.norm(e1)
        e2 = np.cross(a, e1)
        row = []
        for k in range(sides):
            th = 2 * math.pi * k / sides
            p = c + radius * (math.cos(th) * e1 + math.sin(th) * e2)
            row.append(mb.vert(p))
        rings.append((row, s, c))
    for j in range(segs):
        r0, s0, c0 = rings[j]
        r1, s1, c1 = rings[j + 1]
        for k in range(sides):
            k1 = (k + 1) % sides
            uv = [rect_uv(tex, s0, k / sides), rect_uv(tex, s0, (k + 1) / sides),
                  rect_uv(tex, s1, (k + 1) / sides), rect_uv(tex, s1, k / sides)]
            w0 = wind_uv(max(0.0, c0[2] / max(z_top, 1e-3)) ** 1.5 * 0.35, phase)
            w1 = wind_uv(max(0.0, c1[2] / max(z_top, 1e-3)) ** 1.5 * 0.35, phase)
            mb.face([r0[k], r0[k1], r1[k1], r1[k]], uv, [w0, w0, w1, w1])


def lotus_lods(spec):
    P = spec["params"]
    col = P["color"]
    phase = (spec["seed"] * 0.137) % 1.0
    out = {}
    for lod in (0, 1, 2):
        mb = MB()
        zt = P["stem_h"]
        top_est = zt + max(r["length"] for r in P["rings"])
        _stem(mb, (0, 0, -0.02), (0.0, 0.0, zt), 0.009, 4 if lod < 2 else 3, 2 if lod == 0 else 1, "stem", phase,
              top_est, bow=P.get("bow", 0.015))
        rings = P["rings"] if lod == 0 else (P["rings"][:1] if lod == 2 else P["rings"])
        for ri, rg in enumerate(rings):
            n = rg["count"] if lod == 0 else max(4, rg["count"] - (2 if lod == 1 else 3))
            rows = 3 if lod < 2 else 2
            for k in range(n):
                a = 2 * math.pi * (k + 0.5 * ri) / n + rg.get("offset", 0.0)
                tex = f"petal_{col}_{rg['tex']}"
                jit = 1.0 + 0.06 * math.sin(k * 2.3 + ri)
                base = (0.012 * math.cos(a) * (1 + ri * 0.2), 0.012 * math.sin(a) * (1 + ri * 0.2), zt - 0.004 + 0.004 * ri)
                _petal(mb, base, a, rg["length"] * jit, rg["width"], rg["tilt"] + 4 * math.sin(k * 1.7), rg["cup"],
                       rg.get("curl", 0.3), tex, rows, phase, top_est)
        if P.get("open", True) and lod < 2:
            pr, ph = P["pod_r"], P["pod_h"]
            _ring_mesh(mb, 0, 0, zt, pr * 0.65, pr, zt + ph, 8 if lod == 0 else 6, "pod_side",
                       lambda u, v: rect_uv("pod_side", u, v), phase, top_est)
            _disc(mb, 0, 0, zt + ph, pr, 8 if lod == 0 else 6, "pod_top", phase, top_est)
            if lod == 0:
                _ring_mesh(mb, 0, 0, zt + ph * 0.6, pr * 1.02, pr * 1.75, zt + ph + P.get("stamen_h", 0.025), 8,
                           "stamens", lambda u, v: rect_uv("stamens", u, v), phase, top_est)
        if P.get("leaf") and lod < 2:
            lf = P["leaf"]
            mb2 = mb
            n = 12 if lod == 0 else 8
            c = mb2.vert((lf["x"], lf["y"], 0.006))
            ring = []
            for k in range(n):
                a = 2 * math.pi * k / n
                ring.append(mb2.vert((lf["x"] + lf["r"] * math.cos(a), lf["y"] + lf["r"] * math.sin(a),
                                      0.006 + lf.get("cup", 0.02) * (1 + 0.3 * math.sin(a * 3)))))
            for k in range(n):
                a0, a1 = 2 * math.pi * k / n, 2 * math.pi * (k + 1) / n
                uv = [rect_uv("lotus_leaf", 0.5, 0.5), rect_uv("lotus_leaf", 0.5 + 0.47 * math.cos(a0), 0.5 + 0.47 * math.sin(a0)),
                      rect_uv("lotus_leaf", 0.5 + 0.47 * math.cos(a1), 0.5 + 0.47 * math.sin(a1))]
                mb2.face([c, ring[k], ring[(k + 1) % n]], uv, [wind_uv(0, phase)] + [wind_uv(0.06, phase)] * 2)
        out[f"lod{lod}"] = mb.build(f"{spec['id']}__lod{lod}")
    return out


# --------------------------------------------------------------------------------------------- reeds

def _card(mb, base, yaw, width, height, bend, tex, phase, rows=4, lean=0.0):
    d = np.array([math.cos(yaw), math.sin(yaw), 0.0])      # card plane direction (across)
    n = np.array([-math.sin(yaw), math.cos(yaw), 0.0])      # bend direction (card normal)
    grid = []
    for j in range(rows):
        s = j / (rows - 1)
        c = np.array(base) + np.array([0, 0, height * s]) + n * (bend * s ** 2) + d * (lean * s)
        c[2] -= abs(bend) * 0.25 * s ** 2                      # bending shortens the card a little
        row = []
        for q in (-0.5, 0.5):
            p = c + d * width * q
            row.append((mb.vert(p), rect_uv(tex, q + 0.5, s), wind_uv(s ** 1.3, phase)))
        grid.append(row)
    for j in range(rows - 1):
        a, b, c2, e = grid[j][0], grid[j][1], grid[j + 1][1], grid[j + 1][0]
        mb.face([a[0], b[0], c2[0], e[0]], [a[1], b[1], c2[1], e[1]], [a[2], b[2], c2[2], e[2]])


def _cattail(mb, base, height, phase, sides=6, head_len=0.13, head_r=0.024, lean=(0.0, 0.0)):
    top = (base[0] + lean[0], base[1] + lean[1], height)
    _stem(mb, base, (base[0] + lean[0] * 0.86, base[1] + lean[1] * 0.86, height - head_len - 0.01), 0.006,
          3 if sides <= 4 else 4, 2, "stem_reed", phase, height, bow=0.01)
    hb = np.array([base[0] + lean[0] * 0.87, base[1] + lean[1] * 0.87, height - head_len - 0.01])
    ht = np.array([base[0] + lean[0] * 0.98, base[1] + lean[1] * 0.98, height - 0.015])
    rings = []
    for z, c, rf in ((0, hb, 0.85), (1, hb + (ht - hb) * 0.5, 1.0), (2, ht, 0.8)):
        row = [mb.vert(c + np.array([head_r * rf * math.cos(2 * math.pi * k / sides),
                                      head_r * rf * math.sin(2 * math.pi * k / sides), 0])) for k in range(sides)]
        rings.append((row, z / 2.0, c))
    for j in range(2):
        r0, s0, c0 = rings[j]
        r1, s1, c1 = rings[j + 1]
        for k in range(sides):
            k1 = (k + 1) % sides
            uv = [rect_uv("cattail", k / sides, s0), rect_uv("cattail", (k + 1) / sides, s0),
                  rect_uv("cattail", (k + 1) / sides, s1), rect_uv("cattail", k / sides, s1)]
            w = [wind_uv(max(0.0, c0[2] / height) ** 1.3, phase)] * 2 + [wind_uv(max(0.0, c1[2] / height) ** 1.3, phase)] * 2
            mb.face([r0[k], r0[k1], r1[k1], r1[k]], uv, w)
    # caps + spike
    for row, c, sgn in ((rings[0][0], hb, -1), (rings[2][0], ht, 1)):
        cc = mb.vert(c + np.array([0, 0, 0.004 * sgn]))
        for k in range(sides):
            k1 = (k + 1) % sides
            idx = [cc, row[k1], row[k]] if sgn < 0 else [cc, row[k], row[k1]]
            mb.face(idx, [rect_uv("cattail", 0.5, 0.95 if sgn > 0 else 0.05)] * 3, [wind_uv(1.0, phase)] * 3)
    tip = mb.vert((top[0], top[1], height + 0.07))
    for k in range(sides):
        k1 = (k + 1) % sides
        mb.face([rings[2][0][k], rings[2][0][k1], tip], [rect_uv("stem_reed", 0.9, 0.2), rect_uv("stem_reed", 0.9, 0.6),
                                                       rect_uv("stem_reed", 1.0, 0.4)], [wind_uv(1.0, phase)] * 3)


def reeds_lods(spec):
    P = spec["params"]
    rng0 = np.random.default_rng(spec["seed"])
    cards = []
    for i in range(P["cards"]):
        r = P["radius"] * math.sqrt(rng0.uniform(0.05, 1))
        a = rng0.uniform(0, 2 * math.pi)
        cards.append(dict(base=(r * math.cos(a), r * math.sin(a), -0.03), yaw=rng0.uniform(0, math.pi),
                          width=rng0.uniform(*P["width"]), height=rng0.uniform(*P["height"]),
                          bend=rng0.uniform(-1, 1) * P["bend"], tex=P["tex"][i % len(P["tex"])],
                          phase=(0.6180339887 * (i + 1) + spec["seed"] * 0.137) % 1.0,
                          lean=rng0.uniform(-0.06, 0.06)))
    cards.sort(key=lambda c: -c["height"])
    cats = []
    for j in range(P.get("cattails", 0)):
        a = rng0.uniform(0, 2 * math.pi)
        r = P["radius"] * 0.6 * math.sqrt(rng0.uniform(0, 1))
        cats.append(dict(base=(r * math.cos(a), r * math.sin(a), -0.03), height=rng0.uniform(*P["cattail_h"]),
                         lean=(rng0.uniform(-0.08, 0.08), rng0.uniform(-0.08, 0.08)),
                         phase=(0.37 * (j + 1) + spec["seed"] * 0.11) % 1.0))
    out = {}
    for lod in (0, 1, 2):
        mb = MB()
        cl = cards if lod == 0 else (cards[: max(3, len(cards) // 2 + 1)] if lod == 1 else cards[:2])
        for c in cl:
            w = c["width"] * (1.0 if lod == 0 else (1.15 if lod == 1 else 1.4))
            _card(mb, c["base"], c["yaw"] if lod < 2 else c["yaw"], w, c["height"], c["bend"], c["tex"], c["phase"],
                  rows=4 if lod == 0 else 3, lean=c["lean"])
        if lod == 2 and len(cl) >= 2:
            pass
        ct = cats if lod < 2 else cats[:1]
        for c in ct:
            _cattail(mb, c["base"], c["height"], c["phase"], sides=6 if lod == 0 else (4 if lod == 1 else 3),
                     lean=c["lean"])
        out[f"lod{lod}"] = mb.build(f"{spec['id']}__lod{lod}")
    return out


# --------------------------------------------------------------------------------------------- spec

def _flora(i, name, recipe, seed, params, tris, collider=("capsule", "decor", False), group="flora"):
    return {"id": i, "name": name, "kit": KIT, "group": group, "priority": "P1", "recipe": recipe, "seed": seed,
            "params": params, "atlas": "sm_flora_water", "lod0_tris": tris, "budget_class": "bush_lod0",
            "collider": {"shape": collider[0], "kind": collider[1], "blocking": collider[2]},
            "wind": {"uv2": True, "rigidBelow_m": 0.0, "fadeIn_m": 0.3, "amplitude_hint": 0.05},
            "pivot": "water surface (pads, lotus) or ground/waterline (reeds): y = 0"}


F0 = 2026100501


def _legacy_assets():
    A = []
    A.append(_flora("sm_lilypad_01", "lily pad single", "flora.lilypad/1", F0 + 1,
                    {"pads": [{"x": 0, "y": 0, "r": 0.30, "rot": 20, "tex": "pad_a", "cup": 0.014}]}, 60,
                    ("box", "decor_water", False), "lily_pad"))
    A.append(_flora("sm_lilypad_02", "lily pad cluster of 3", "flora.lilypad/1", F0 + 2,
                    {"pads": [{"x": 0.0, "y": 0.0, "r": 0.26, "rot": 140, "tex": "pad_a"},
                              {"x": 0.42, "y": 0.18, "r": 0.19, "rot": 260, "tex": "pad_b", "notch": 32},
                              {"x": 0.12, "y": -0.40, "r": 0.15, "rot": 30, "tex": "pad_a", "notch": 24}]}, 160,
                    ("box", "decor_water", False), "lily_pad"))
    A.append(_flora("sm_lilypad_03", "lily pad cluster of 5 with a curled young pad", "flora.lilypad/1", F0 + 3,
                    {"pads": [{"x": 0.0, "y": 0.0, "r": 0.24, "rot": 70, "tex": "pad_b"},
                              {"x": -0.42, "y": 0.10, "r": 0.20, "rot": 200, "tex": "pad_c"},
                              {"x": 0.30, "y": 0.34, "r": 0.17, "rot": 300, "tex": "pad_a"},
                              {"x": 0.36, "y": -0.26, "r": 0.13, "rot": 120, "tex": "pad_c", "notch": 34},
                              {"x": -0.12, "y": -0.38, "r": 0.10, "rot": 10, "tex": "pad_a", "young": True,
                               "lift": 0.01, "curl": 0.06, "cup": 0.02}]}, 260,
                    ("box", "decor_water", False), "lily_pad"))
    for color in ("pink", "white"):
        A.append(_flora(f"sm_lotus_bud_{color}", f"lotus bud ({color})", "flora.lotus/1", F0 + (11 if color == "pink" else 12),
                        {"color": color, "open": False, "stem_h": 0.30, "bow": 0.02,
                         "rings": [{"count": 4, "length": 0.105, "width": 0.07, "tilt": 9, "cup": 0.45, "curl": -0.2, "tex": "outer"},
                                   {"count": 4, "length": 0.095, "width": 0.06, "tilt": 3, "cup": 0.5, "curl": -0.1, "tex": "inner",
                                    "offset": 0.4}],
                         "leaf": {"x": 0.16, "y": -0.07, "r": 0.17, "cup": 0.015}}, 150, ("capsule", "decor_water", False), "lotus"))
        A.append(_flora(f"sm_lotus_open_{color}", f"lotus open flower ({color})", "flora.lotus/1", F0 + (13 if color == "pink" else 14),
                        {"color": color, "open": True, "stem_h": 0.20, "bow": 0.015, "pod_r": 0.026, "pod_h": 0.022,
                         "stamen_h": 0.022,
                         "rings": [{"count": 7, "length": 0.115, "width": 0.062, "tilt": 64, "cup": 0.32, "curl": 0.35, "tex": "outer"},
                                   {"count": 7, "length": 0.10, "width": 0.056, "tilt": 36, "cup": 0.38, "curl": 0.15, "tex": "inner",
                                    "offset": 0.25}],
                         "leaf": {"x": -0.17, "y": 0.10, "r": 0.19, "cup": 0.018}}, 270, ("capsule", "decor_water", False), "lotus"))
    A.append(_flora("sm_reeds_01", "tall cattail clump", "flora.reeds/1", F0 + 21,
                    {"cards": 8, "radius": 0.24, "width": [0.36, 0.48], "height": [1.05, 1.5], "bend": 0.22,
                     "tex": ["reeds_tall", "reeds_mixed", "reeds_tall", "reeds_mixed", "reeds_tall"],
                     "cattails": 3, "cattail_h": [1.15, 1.55]}, 230, ("capsule", "decor", False), "reeds"))
    A.append(_flora("sm_reeds_02", "medium reed clump", "flora.reeds/1", F0 + 22,
                    {"cards": 7, "radius": 0.22, "width": [0.34, 0.46], "height": [0.75, 1.1], "bend": 0.2,
                     "tex": ["reeds_tall", "reeds_sedge", "reeds_mixed"], "cattails": 1, "cattail_h": [0.95, 1.12]}, 160,
                    ("capsule", "decor", False), "reeds"))
    A.append(_flora("sm_reeds_03", "short sedge clump at the waterline", "flora.reeds/1", F0 + 23,
                    {"cards": 7, "radius": 0.26, "width": [0.36, 0.5], "height": [0.45, 0.72], "bend": 0.16,
                     "tex": ["reeds_short", "reeds_sedge", "reeds_short"], "cattails": 0, "cattail_h": [0, 0]}, 60,
                    ("capsule", "decor", False), "reeds"))
    return A


def assets():
    """Brief 06: four single pads, three bloom stages, three metre-scale clumps."""
    result = []
    for i, radius in enumerate((.15, .23, .30, .35), 1):
        result.append(_flora(f"sm_lilypad_{i:02}", f"notched lily pad {i}", "flora.lilypad/1", F0+i,
            {"seg":12,"pads":[{"x":0,"y":0,"r":radius,"rot":i*47,"tex":("pad_a","pad_b","pad_c","pad_a")[i-1],
             "cup":.006+i*.001,"wave":.002,"notch":24+i*2}]},40,("none","decor_water",False),"lily_pad"))
    for i, (stage, tilt, count) in enumerate((("open",64,7),("half",35,6),("bud",7,4))):
        result.append(_flora(f"sm_lotus_{stage}", f"pink lotus {stage}", "flora.lotus/1", F0+11+i,
            {"color":"pink","open":stage!="bud","stem_h":.20 if stage=="open" else .30,"bow":.012,
             "pod_r":.026,"pod_h":.022,"stamen_h":.022,
             "rings":[{"count":count,"length":.14,"width":.082,"tilt":tilt,"cup":.32,"curl":.25,"tex":"outer"},
                      {"count":count,"length":.115,"width":.070,"tilt":max(3,tilt-24),"cup":.40,"curl":.10,"tex":"inner","offset":.25}]},
            200,("none","decor_water",False),"lotus"))
    for i, (cats, ht) in enumerate(((2,(1.35,1.70)),(1,(1.15,1.45)),(0,(1.05,1.25))),1):
        result.append(_flora(f"sm_reeds_{i:02}",f"reed and cattail clump {i}","flora.reeds/1",F0+20+i,
            {"cards":8,"radius":.24,"width":[.26,.38],"height":list(ht),"bend":.16,
             "tex":["reeds_tall","reeds_sedge","reeds_mixed"],"cattails":cats,"cattail_h":[ht[0],min(1.73,ht[1]+.03)]},
            300,("none","decor",False),"reeds"))
    return result


def build_lods(spec):
    r = spec["recipe"]
    if r == "flora.lilypad/1":
        return lilypad_lods(spec)
    if r == "flora.lotus/1":
        return lotus_lods(spec)
    if r == "flora.reeds/1":
        return reeds_lods(spec)
    raise ValueError(r)
