"""Craft-only modelling helpers; shared stone-owned helpers stay read-only."""
from __future__ import annotations
import math
import numpy as np
import bpy
import bmesh
from mathutils import Vector
import np_lib as L
from np_craft_texture import uv_rect

class Craft:
    def __init__(self,seed,revision=1,lod=0):
        self.parts=[];self.rng=np.random.default_rng(seed);self.revision=revision;self.lod=lod;self.dark_timber=False
    def finish(self,ob,tile='wood',bevel=0,wind=False):
        weathered=tile=='weathered'
        if weathered:tile='wood'
        if bevel and self.lod==0:L.bevel(ob,bevel,segments=1);L.apply_modifiers(ob)
        bpy.context.view_layer.update()
        L.apply_transform(ob)
        bm=bmesh.new();bm.from_mesh(ob.data)
        bmesh.ops.recalc_face_normals(bm,faces=list(bm.faces));bm.to_mesh(ob.data);bm.free();ob.data.update()
        me=ob.data;v=L.verts(me);mn=v.min(axis=0);span=np.maximum(v.max(axis=0)-mn,.001)
        # Blender cone primitives arrive with an autogenerated UVMap.
        while me.uv_layers:me.uv_layers.remove(me.uv_layers[0])
        layer=me.uv_layers.new(name='UVMap');uv=np.zeros((len(me.loops),2),dtype=np.float32)
        wr=me.uv_layers.new(name='wind');wu=np.zeros_like(uv);wu[:,1]=.5
        u0,v0,du,dv=uv_rect(tile)
        if tile in ('sapphire','terracotta','slate') and not wind:du*=.08
        if weathered:u0+=du*.20;du*=.60
        for p in me.polygons:
            n=np.abs(p.normal);axis=int(np.argmax(n));ax=(1,2) if axis==0 else (0,2) if axis==1 else (0,1)
            # Grain along the longer visible axis; full tile gives paired end studs.
            if span[ax[0]]<span[ax[1]] and tile=='wood':ax=ax[::-1]
            for li in p.loop_indices:
                q=(v[me.loops[li].vertex_index]-mn)/span
                uv[li]=(u0+q[ax[0]]*du,v0+q[ax[1]]*dv)
                if wind:wu[li,0]=.12*(1-q[1])*math.sin(math.pi*q[0])
        layer.data.foreach_set('uv',uv.ravel());wr.data.foreach_set('uv',wu.ravel());me.uv_layers.active=layer
        value=np.clip(.86+.12*(v[:,2]-mn[2])/span[2],.75,1)
        if self.revision>=2:value*=self.rng.uniform(.96,1.04)
        if self.revision>=2:value=np.clip(value+.025,0,1)
        rgb=np.repeat(value[:,None],3,axis=1)
        if tile=='wood' and self.dark_timber and not weathered:rgb*=np.array([.34,.42,.57])
        if weathered:rgb*=np.array([.82,.93,1.0])
        L.set_corner_color_byte(ob,'Col',rgb)
        self.parts.append(ob);return ob
    def box(self,size,center,tile='wood',bevel=.015,rot=0,wind=False):
        ob=L.box_object('craft_part',size,center)
        if rot:
            v=L.verts(ob.data);c=np.array(center);q=v-c;co,si=math.cos(rot),math.sin(rot)
            q[:,:2]=q[:,:2]@np.array([[co,si],[-si,co]]);L.set_verts(ob.data,q+c)
        return self.finish(ob,tile,bevel,wind)
    def beam(self,a,b,r=.055,tile='wood',sides=6):
        if self.lod>=2:sides=max(4,sides//2)
        elif self.lod==1:sides=max(5,round(sides*.75))
        a,b=Vector(a),Vector(b);mid=(a+b)/2
        bpy.ops.mesh.primitive_cone_add(vertices=sides,radius1=r,radius2=r*.94,depth=(b-a).length,location=mid)
        ob=bpy.context.object;ob.rotation_euler=(b-a).to_track_quat('Z','Y').to_euler()
        return self.finish(ob,tile)
    def lathe(self,profile,center=(0,0,0),tile='stone',n=12,phase=0):
        if self.lod>=2:n=max(6,n//2)
        elif self.lod==1:n=max(8,round(n*.75))
        vs=[];rings=[];faces=[]
        for r,z in profile:
            if r==0:rings.append([len(vs)]);vs.append((center[0],center[1],center[2]+z));continue
            ring=[]
            for k in range(n):
                a=2*math.pi*k/n+phase;ring.append(len(vs));vs.append((center[0]+r*math.cos(a),center[1]+r*math.sin(a),center[2]+z))
            rings.append(ring)
        for a,b in zip(rings,rings[1:]):
            for k in range(n):
                k1=(k+1)%n
                if len(a)==1:faces.append([a[0],b[k1],b[k]])
                elif len(b)==1:faces.append([a[k],a[k1],b[0]])
                else:faces.append([a[k],a[k1],b[k1],b[k]])
        if len(rings[0])>1:faces.append(rings[0][::-1])
        if len(rings[-1])>1:faces.append(rings[-1])
        return self.finish(L.mesh_from_arrays('craft_lathe',vs,faces),tile)
    def wedge(self,r0,r1,a0,a1,z0,z1,tile='stone',center=(0,0)):
        vs=[(center[0]+r*math.cos(a),center[1]+r*math.sin(a),z) for z in (z0,z1) for r in (r0,r1) for a in (a0,a1)]
        faces=[[0,1,3,2],[4,6,7,5],[0,4,5,1],[2,3,7,6],[0,2,6,4],[1,5,7,3]]
        return self.finish(L.mesh_from_arrays('craft_wedge',vs,faces),tile)
    def awning(self,w,d,z,tile,peak=False,cloth=True):
        # Closed cloth volume, shallow sag, scalloped lower edge at the front.
        nx=max(6,round(w/(.35 if self.lod>=2 else .25 if self.lod==1 else .15)));v=[];f=[]
        for zoff in (0,-.045):
            for j in range(3):
                y=-d/2+d*j/2
                for i in range(nx+1):
                    x=-w/2+w*i/nx
                    zz=z+(.38*(1-abs(y)/(d/2)) if peak else .25*y/d)-.07*math.sin(math.pi*i/nx)
                    if j==0:zz-=.055*(.5+.5*math.cos(i*math.pi))
                    v.append((x,y,zz+zoff))
        plane=3*(nx+1)
        for off in (0,plane):
            for j in range(2):
                for i in range(nx):
                    a=off+j*(nx+1)+i;quad=[a,a+1,a+nx+2,a+nx+1];f.append(quad if off==0 else quad[::-1])
        border=list(range(nx+1))+[j*(nx+1)+nx for j in (1,2)]+list(range(3*(nx+1)-2,2*(nx+1)-1,-1))+[nx+1]
        for a,b in zip(border,border[1:]+border[:1]):f.append([a,b,b+plane,a+plane])
        roof=self.finish(L.mesh_from_arrays('cloth_canopy',v,f),tile,wind=cloth)
        if self.revision>=2 and cloth:
            vv=[];ff=[]
            for y in (-d/2-.022,-d/2+.022):
                for bottom in (False,True):
                    for i in range(nx+1):
                        x=-w/2+w*i/nx;zt=z+(-.125 if not peak else 0)-.07*math.sin(math.pi*i/nx)-.055*(.5+.5*math.cos(i*math.pi))
                        vv.append((x,y,zt-(.16+.025*math.sin(math.pi*i)) if bottom else zt-.015))
            n=nx+1
            for i in range(nx):
                ff.extend([[i,i+1,n+i+1,n+i],[2*n+i,3*n+i,3*n+i+1,2*n+i+1],
                           [i,2*n+i,2*n+i+1,i+1],[n+i,n+i+1,3*n+i+1,3*n+i]])
            ff.extend([[0,n,3*n,2*n],[nx,2*n+nx,3*n+nx,n+nx]])
            self.finish(L.mesh_from_arrays('scalloped_valance',vv,ff),tile,wind=True)
        return roof
    def joined(self,name):return L.join(self.parts,name)

def construct(spec,revision=1,lod=0):
    c=Craft(spec['seed'],revision,lod);p=spec['params'];kind=spec['recipe'].split('.')[1].split('/')[0]
    c.dark_timber=kind=='stall' and revision>=6
    hulls=[];metadata={}
    def hull(size,center):hulls.append(L.box_object('collider_part',size,center))
    def wall(length=3,off=(0,0),axis=0,height=1.1):
        # Three staggered masonry courses: deliberate large forms and cap.
        for row in range(3):
            for i in range(4):
                x=-length/2+(i+.5)*length/4;y=0
                if axis:x,y=y,x
                c.box((length/4-.025,.48,height/3-.015) if not axis else (.48,length/4-.025,height/3-.015),
                      (off[0]+x,off[1]+y,(row+.5)*height/3),'stone',.025 if revision>=2 else .012)
        c.box((length,.51,.085) if not axis else (.51,length,.085),(off[0],off[1],height+.02),'turf',.018)
        hull((length,.5,height) if not axis else (.5,length,height),(off[0],off[1],height/2))
    def deck(length,width,bridge=False):
        n=round(length/.267)
        for i in range(n):c.box((width,length/n-.015,.115),(0,-length/2+(i+.5)*length/n,.0625),'wood',.014)
        for x in (-width*.4,width*.4):c.box((.14,length,.16),(x,0,-.075),'wood',.015)
        for x in (-width*.44,width*.44):
            for y in (-length*.42,length*.42):c.beam((x,y,-.65),(x,y,.95 if not bridge else .12),.10)
        metadata.update(walk_surface={'status':'REQUIRES_WALK_SURFACE','top_y':.12,'extent':[width,length],
                         'reason':'Root must integrate client and server support; placement height alone is not proof.'})
        hull((width,length,.12),(0,0,.06))
    def boat(length,beam,skiff=False):
        # Clinker hull: closed section bands, narrow keel, flared sheer and raised prow.
        n=16 if lod<2 else 8;v=[];faces=[]
        for row,(scale,z) in enumerate(((.18,0),(.65,.16),(1,.52),(.87,.57),(.65,.23))):
            for i in range(n):
                a=2*math.pi*i/n;xx=beam/2*math.sin(a)*scale;yy=length/2*math.cos(a)*(.88+.12*scale)
                zz=z+.24*abs(math.cos(a))**8;v.append((xx,yy,zz))
        for row in range(4):
            for i in range(n):j=(i+1)%n;faces.append([row*n+i,row*n+j,(row+1)*n+j,(row+1)*n+i])
        faces.extend([list(range(n-1,-1,-1)),list(range(4*n,5*n))])
        hull_ob=c.finish(L.mesh_from_arrays('clinker_hull',v,faces),'wood')
        if revision>=3:
            height=L.verts(hull_ob.data)[:,2]
            shade=np.where(height<.20,.47,.83)
            L.set_corner_color_byte(hull_ob,'Col',np.repeat(shade[:,None],3,axis=1))
        if skiff and revision>=4:
            for row,(scale,z) in enumerate(((.62,.15),(.80,.32),(.98,.49))):
                vv=[];ff=[]
                for rr,zz in ((scale,z-.08),(scale+.035,z+.055),(scale+.015,z+.055),(scale-.02,z-.08)):
                    for i in range(n):
                        a=math.tau*i/n;vv.append((beam/2*math.sin(a)*rr,length/2*math.cos(a)*(.88+.12*rr),zz+.24*abs(math.cos(a))**8))
                for k in range(4):
                    for i in range(n):j=(i+1)%n;kn=(k+1)%4;ff.append([k*n+i,k*n+j,kn*n+j,kn*n+i])
                lap=c.finish(L.mesh_from_arrays('overlapping_clinker_strake',vv,ff),'wood')
                L.set_corner_color_byte(lap,'Col',np.full((len(lap.data.vertices),3),(.68,.86,.70)[row]))
        for y in (-length*.19,length*.17):c.box((beam*.77,.23,.10),(0,y,.46),'wood',.025)
        for side in (-1,1):
            for i in range(6):
                a0=math.pi*(i+.16)/6;a1=math.pi*(i+.84)/6
                a=(side*beam*.47*math.sin(a0),length*.47*math.cos(a0),.54+.20*abs(math.cos(a0))**8)
                b=(side*beam*.47*math.sin(a1),length*.47*math.cos(a1),.54+.20*abs(math.cos(a1))**8)
                c.beam(a,b,.045,'sapphire' if skiff else 'rope')
        hull((beam*.8,length*.75,.5),(0,0,.25))
        metadata.update(waterline_m=.20,placement_at_water_y=-.20,buoyant_decorative=True)
    def goods(shape,origin=(0,0,0)):
        ox,oy,oz=origin
        if shape=='bread' and revision>=6:
            basket=c.lathe([(0,0),(.20,.015),(.30,.22),(.31,.28),(.265,.30),(.245,.24),(.17,.065),(0,.065)],(ox,oy,oz),'rope',n=12)
            v=L.verts(basket.data);v[:,1]=oy+(v[:,1]-oy)*.72;L.set_verts(basket.data,v)
            for h,r in ((.10,.25),(.18,.285),(.27,.31)):
                band=c.lathe([(r,h-.014),(r+.017,h),(r,h+.014)],(ox,oy,oz),'rope',n=12)
                v=L.verts(band.data);v[:,1]=oy+(v[:,1]-oy)*.72;L.set_verts(band.data,v)
            count=8 if lod<2 else 5
            for k in range(count):
                a=math.pi*k/count;b=math.pi*(k+1)/count
                c.beam((ox+.28*math.cos(a),oy,oz+.25+.28*math.sin(a)),(ox+.28*math.cos(b),oy,oz+.25+.28*math.sin(b)),.025,'rope',5)
        elif shape=='fish' and revision>=6:
            c.box((.66,.43,.045),(ox,oy,oz+.025),'wood',.008)
            for x in (-.30,.30):c.box((.055,.43,.13),(ox+x,oy,oz+.085),'wood',.008)
            for y in (-.19,.19):c.box((.61,.05,.13),(ox,oy+y,oz+.085),'wood',.008)
        elif shape!='jars':
            c.box((.62,.44,.065),(ox,oy,oz+.035),'wood',.008)
            for x in (-.29,.29):c.box((.065,.44,.32),(ox+x,oy,oz+.19),'wood',.008)
            for y in (-.2,.2):
                for row in range(2):c.box((.58,.045,.105),(ox,oy+y,oz+.105+row*.15),'wood',.007)
        for i in range(6 if shape in ('apples','carrots') else 3 if shape=='bread' else 2):
            x=ox+(i%3-1)*.155;y=oy+(i//3-.5)*.14;z=oz+.29
            if shape=='apples':c.lathe([(0,0),(.07,.015),(.085,.065),(.055,.135),(0,.145)],(x,y,z),'apple',n=8)
            elif shape=='carrots':c.lathe([(0,0),(.027,.035),(.044,.21),(0,.22)],(x,y,z),'carrot',n=6)
            elif shape=='bread':c.lathe([(0,0),(.07,.005),(.105,.045),(.09,.14),(0,.18)],(x,y,z),'bread',n=8)
            elif shape=='fish':c.beam((ox-.18,oy+(i-.5)*.13,oz+(.10 if revision>=6 else .28)),(ox+.20,oy+(i-.5)*.13,oz+(.10 if revision>=6 else .28)),.065,'fish',8)
            else:c.lathe([(0,0),(.14,.02),(.20,.22),(.16,.4),(.08,.47),(.10,.52),(.075,.54),(.065,.47),(0,.46)],(ox+(i-.5)*.4,oy,oz),'clay',n=12)
    if kind=='hut':
        radius=p['radius'];rows=(7 if revision<2 else 6) if lod<2 else 4;segs=24 if lod<2 else 12;course=(3.15 if revision<2 else 2.70)/rows
        for row in range(rows):
            z0=row*course;z1=z0+course-.015;rr=radius*math.sqrt(max(.06,1-(z0/3.65)**2))
            for i in range(segs):
                stagger=.5*(row%2) if revision>=2 else 0
                a0=2*math.pi*(i+stagger)/segs+.008;a1=2*math.pi*(i+1+stagger)/segs-.008
                mid=(a0+a1)/2
                if z0<2.15 and math.sin(mid)<-.6 and min(abs(rr*math.cos(a0)),abs(rr*math.cos(a1)))<1.10:continue
                c.wedge(rr-.32,rr,a0,a1,z0,z1,'stone')
        # Turf shell, each concentric band overlaps physically and reads as a cap.
        roof=[(0,3.60),(.50,3.62),(1.1,3.51),(1.8,3.20),(2.30,2.83),(2.55,2.62),(2.40,2.54),(1.70,3.07),(.8,3.43),(0,3.45)]
        c.lathe(roof[::-1] if revision>=2 else roof,tile='turf',n=24)
        for x in (-1.08,1.08):c.box((.23,.46,2.24),(x,-2.82,1.12),'wood',.035);hull((.3,.6,2.3),(x,-2.78,1.15))
        if revision>=3:
            for x in (-1.49,1.49):
                for row in range(5):c.box((.76,.85,.425),(x,-2.55,.22+row*.44),'stone',.025)
        c.box((2.42,.48,.26),(0,-2.82,2.26),'wood',.035)
        if p.get('chimney'):c.box((.55,.55,1.2),(1.1,.8,3.30),'stone',.03);c.box((.67,.67,.18),(1.1,.8,3.94),'stone',.03)
        # Opening-aware hull wedges: never a convex hull across the door.
        for i in range(24):
            a=(i+.5)*math.tau/24
            if math.sin(a)<-.91:continue
            ob=L.box_object('hut_compound',(.34,.81,2.5));ob.rotation_euler.z=a;ob.location=(2.7*math.cos(a),2.7*math.sin(a),1.25);bpy.context.view_layer.update();L.apply_transform(ob);hulls.append(ob)
        hull((2.1,.5,1.3),(0,-2.45,2.85));metadata['door_opening']={'width_m':1.9,'height_m':2.15,'front':'+Z','compound':True}
    elif kind=='wall':
        shape=p['shape']
        if shape=='gate':
            for x in (-1.28,1.28):c.box((.43,.54,1.25),(x,0,.625),'stone',.03);hull((.43,.54,1.25),(x,0,.625))
            metadata['door_opening']={'width_m':2.13,'height_m':None,'compound':True}
        elif shape=='corner':wall(1.5,(-.75,0));wall(1.5,(0,.75),1)
        else:wall()
    elif kind=='well':
        for row in range(2):
            for i in range(12):a=i*math.tau/12+.012;c.wedge(.54,.8,a,a+math.tau/12-.024,row*.32,(row+1)*.32-.015)
        for x in (-.68,.68):c.box((.17,.17,2.25),(x,0,1.12),'wood',.022)
        c.beam((-.8,0,1.63),(.8,0,1.63),.10);c.beam((0,0,.45),(0,0,1.63),.022,'rope')
        c.awning(1.95,1.45,2.30,'slate',True,cloth=False)
        c.lathe([(0,0),(.16,.02),(.20,.29),(.16,.31),(.13,.06),(0,.06)],(.88,-.45,.03),'wood',n=10)
        hull((1.6,1.6,.65),(0,0,.325));metadata['well_void']={'radius':.54,'decorative_only':True}
    elif kind=='skep':
        h=p['height'];r=p['radius'];c.lathe([(0,0),(r,.03),(r*.98,h*.30),(r*.84,h*.65),(r*.5,h*.92),(0,h)],tile='thatch',n=12)
        for z,rf in ((.25,.99),(.53,.90),(.78,.70)):
            c.lathe([(r*rf,h*z-.025),(r*rf+.024,h*z),(r*rf,h*z+.028)],tile='rope',n=12)
        hull((r*1.8,r*1.8,h),(0,0,h/2))
    elif kind=='campfire':
        for i in range(10):a=i*math.tau/10;c.box((.28,.22,.16),(.53*math.cos(a),.53*math.sin(a),.09),'stone',.04,rot=a)
        for a in (0,math.pi/3,2*math.pi/3):c.beam((-.42*math.cos(a),-.42*math.sin(a),.13),(.42*math.cos(a),.42*math.sin(a),.13),.08)
        for x in (-.7,.7):c.beam((x,-.20,0),(x,0,1.05),.048);c.beam((x,.20,0),(x,0,1.05),.048)
        c.beam((-.83,0,1.04),(.83,0,1.04),.035,'iron')
        for y in (-1.18,1.18):c.beam((-.8,y,.18),(.8,y,.18),.18)
        hull((1.1,1.1,.26),(0,0,.13));metadata['fire_anchor']=[0,.22,0]
    elif kind=='fence':
        for x in (-1.2,0,1.2):c.box((.13,.16,1.02),(x,0,.51),'wood',.018)
        for z in (.34,.78):c.box((2.5,.10,.15),(0,0,z),'wood',.018)
        hull((2.5,.18,1),(0,0,.5))
    elif kind=='firewood':
        for row in range(3):
            for j in range(4-row):c.beam((-.62,(j-(3-row)/2)*.23,.12+row*.19),(.62,(j-(3-row)/2)*.23,.12+row*.19),.11)
        hull((1.3,.9,.65),(0,0,.325))
    elif kind=='trough':
        c.box((1.6,.63,.13),(0,0,.13),'wood',.02)
        for y in (-.30,.30):c.box((1.6,.10,.46),(0,y,.37),'wood',.02)
        for x in (-.76,.76):c.box((.10,.55,.46),(x,0,.37),'wood',.02)
        for x in (-.55,.55):c.box((.18,.77,.15),(x,0,.08),'wood',.02)
        hull((1.6,.7,.6),(0,0,.3))
    elif kind in ('pier','bridge'):
        deck(p['length'],p['width'],kind=='bridge')
        if kind=='bridge':
            for x in (-1.58,1.58):
                for j in range(5):
                    for row in range(2):c.box((.45,.78,.41),(x,-1.6+j*.8,.34+row*.42),'stone',.027)
                c.box((.49,4.03,.08),(x,0,1.08),'turf',.02);hull((.48,4,1),(x,0,.61))
        else:
            for x in (-.88,.88):c.beam((x,-1.7,.70),(x,1.7,.70),.022,'rope')
            if p['end']:c.beam((-.88,1.7,.7),(.88,1.7,.7),.022,'rope')
    elif kind=='post':
        c.beam((0,0,-.6),(0,0,1.15),.13)
        for z in (.73,.80,.87):c.lathe([(.125,z-.02),(.16,z),(.125,z+.02)],tile='rope',n=10)
        c.beam((0,0,.83),(0,1.6,.63),.025,'rope');hull((.26,.26,1.1),(0,0,.55))
    elif kind=='ladder':
        for x in (-.32,.32):c.beam((x,0,-1.5),(x,0,.85),.055)
        for z in np.arange(-1.3,.8,.29):c.beam((-.32,0,z),(.32,0,z),.04)
        hull((.75,.15,2.35),(0,0,-.325))
    elif kind=='bollard':
        c.lathe([(0,0),(.18,.02),(.14,.50),(.24,.51),(.24,.63),(0,.65)],tile='wood',n=10);hull((.4,.4,.65),(0,0,.325))
    elif kind in ('boat','skiff'):
        boat(p['length'],p['beam'],kind=='skiff')
        if kind=='skiff':
            c.beam((0,0,.22),(0,0,5.5),.10)
            c.beam((0,-.15,3.6),(0,2.05,3.4),.085)
            if revision>=4:
                axis=Vector((0,2.02,-.18));length=axis.length
                profile=[(0,0)]+[(.12+.10*math.sin(math.pi*j/8)**.5+.014*math.sin(j*2.8),length*j/8) for j in range(9)]+[(0,length)]
                sail=c.lathe(profile,tile='cream',n=10);sail.rotation_euler=axis.to_track_quat('Z','Y').to_euler();sail.location=(0,-.12,3.65);bpy.context.view_layer.update();L.apply_transform(sail)
                for s in (.25,.75):
                    z=length*s;r=.12+.10*math.sin(math.pi*s)**.5+.02
                    tie=c.lathe([(r,z-.025),(r+.025,z),(r,z+.025)],tile='rope',n=10);tie.rotation_euler=axis.to_track_quat('Z','Y').to_euler();tie.location=(0,-.12,3.65);bpy.context.view_layer.update();L.apply_transform(tie)
                segments=24 if lod<2 else 12
                for i in range(segments):
                    def rp(j):
                        t=j/segments;a=t*math.tau*2.5;r=.045+.23*t;return (.28+r*math.cos(a),1.15+r*math.sin(a),.265)
                    c.beam(rp(i),rp(i+1),.025,'rope',6)
            else:c.beam((0,-.12,3.65),(0,1.9,3.47),.20,'cream',10)
            if revision>=5:
                outline=[(-2.50,.70),(-2.80,.75),(-2.94,.96),(-2.87,1.15),(-2.72,1.24),(-2.60,1.12),(-2.63,.99),(-2.74,.95),(-2.66,.84),(-2.48,.81)]
                vv=[(x,y,z) for x in (-.11,.11) for y,z in outline];n=len(outline)
                ff=[list(range(n-1,-1,-1)),list(range(n,2*n))]+[[i,(i+1)%n,(i+1)%n+n,i+n] for i in range(n)]
                c.finish(L.mesh_from_arrays('carved_prow_scroll',vv,ff),'sapphire',.013)
            else:c.beam((0,-2.55,.70),(0,-2.68,1.17),.14,'sapphire',8)
            c.beam((0,2.55,.50),(0,2.55,1.45),.07);c.box((.24,.20,.35),(0,2.55,1.32),'iron',.025)
            if revision>=4:c.box((.145,.023,.225),(0,2.438,1.32),'cream',.01)
            metadata['lantern_anchor']=[0,1.32,-2.55]
    elif kind=='driftwood':
        length=p['length']
        if revision>=6:
            rings=6 if lod<2 else 4;sides=7 if lod<2 else 5;v=[];f=[]
            phase=c.rng.uniform(-.4,.4)
            for j in range(rings):
                t=j/(rings-1);r=.14*(1-.35*t);cx=-length/2+length*t;cy=.10*math.sin(math.pi*t)+.03*math.sin(3*math.pi*t+phase);cz=.14+.025*math.sin(math.pi*t)
                for k in range(sides):
                    a=-math.pi/2+math.tau*k/sides;wear=1+.07*math.sin(k*2.3+j*.8+phase)
                    v.append((cx+.015*math.cos(a*3)*(1 if j in (0,rings-1) else .2),cy+r*math.cos(a)*wear,cz+r*math.sin(a)*.8))
            for j in range(rings-1):
                for k in range(sides):kk=(k+1)%sides;f.append([j*sides+k,j*sides+kk,(j+1)*sides+kk,(j+1)*sides+k])
            f.extend([list(range(sides-1,-1,-1)),list(range((rings-1)*sides,rings*sides))])
            c.finish(L.mesh_from_arrays('weathered_curved_trunk',v,f),'weathered')
            c.beam((-.12,0,.14),(.20*length,.36,.25),.065,'weathered')
        else:
            c.beam((-length/2,0,.12),(length/2,.1,.17),.12);c.beam((-.15,0,.14),(.3,.42,.28),.065)
        metadata['decorative']=True
    elif kind=='rod_rack':
        for x in (-.6,.6):c.beam((x,0,0),(x,0,.90),.06)
        c.beam((-.68,0,.82),(.68,0,.82),.065)
        for x in (-.38,0,.38):c.beam((x,-.28,.08),(x,.22,1.70),.022)
        hull((1.4,.25,.9),(0,0,.45))
    elif kind=='gate':
        for x in (-2.0,2.0):
            for row in range(5):c.box((.9,.90,.57),(x,0,.30+row*.59),'stone',.04)
            c.box((1.08,1.08,.22),(x,0,3.12),'turf',.03);hull((.95,.95,3.2),(x,0,1.6))
        c.box((4.85,.62,.39),(0,0,3.35),'wood',.045)
        c.box((4.98,.74,.15),(0,0,3.62),'slate',.04)
        hull((4.9,.7,.6),(0,0,3.5));metadata['door_opening']={'width_m':3.05,'height_m':3.15,'compound':True}
    elif kind=='brazier':
        shape=p['shape'];z=.99 if shape=='pillar' else .97 if shape=='tripod' else .18;r=.45 if shape=='pillar' else .35 if shape=='tripod' else .24
        if shape=='pillar':
            c.box((.83,.83,.68),(0,0,.34),'stone',.07);c.box((1.2,1.2,.14),(0,0,.72),'stone',.05)
        elif shape=='tripod':
            for i in range(3):a=i*math.tau/3;c.beam((.33*math.cos(a),.33*math.sin(a),0),(.20*math.cos(a),.20*math.sin(a),z),.047,'iron')
        else:c.box((.12,.2,.50),(0,.25,.25),'iron',.01);c.beam((0,.25,.15),(0,0,z),.055,'iron')
        c.lathe([(0,z-.16),(r*.58,z-.13),(r,z+.05),(r,z+.12),(r*.86,z+.13),(r*.68,z-.05),(0,z-.06)],tile='iron',n=12)
        c.lathe([(0,z-.04),(r*.65,z-.04),(0,z-.032)],tile='coal',n=12)
        for i in range(4):a=i*math.tau/4;c.beam((r*.48*math.cos(a),r*.48*math.sin(a),z-.23),(r*.92*math.cos(a),r*.92*math.sin(a),z+.08),.045,'iron')
        hull((r*1.8,r*1.8,z+.1),(0,0,(z+.1)/2));metadata['fire_anchor']=[0,z+.1,0]
    elif kind=='stall':
        shape=p['shape'];w=p['width'];d=1.6
        for x in (-w/2+.07,w/2-.07):
            base=.52 if shape=='C' and revision>=4 else 0
            for y in ((.65,) if shape=='B' else (-.65,.65)):c.box((.14,.14,2.42-base),(x,y,(2.42+base)/2),'wood',.02)
        for y in (-.65,.65):c.box((w,.16,.18),(0,y,2.38),'wood',.02)
        c.box((w,1.1,.12),(0,0,.95),'wood',.022)
        c.box((w,.12,.38 if shape=='C' and revision>=4 else .76),(0,-.50,.70 if shape=='C' and revision>=4 else .50),'wood',.018)
        for x in (-w/2+.25,w/2-.25):c.beam((x,-.48,1.58),(x+(.35 if x<0 else -.35),-.48,2.36),.045)
        if shape=='B':
            c.box((.65,1.0,.12),(w/2-.3,-.73,.95),'wood',.018)
            for x in (-w/2+.07,w/2-.07):
                c.beam((x,.65,1.80),(x,-.68,2.45),.07)
            for x in (-.75,0,.75):
                c.lathe([(0,0),(.12,.03),(.10,.25),(0,.38)],(x,.53,1.7),'turf',n=6)
                c.beam((x,.53,2.05),(x,.53,2.36),.017,'rope')
        if shape=='C':
            for x in (-1.08,1.08):
                ob=c.lathe([(0,0),(.37,.02),(.40,.09),(.37,.16),(0,.18)],tile='wood',n=24 if revision>=6 else 12)
                if revision>=6:
                    colors=ob.data.color_attributes['Col']
                    for face in ob.data.polygons:
                        if abs(face.normal.z)>.80:
                            a=math.atan2(face.center.y,face.center.x);shade=.93 if math.cos(a*6)>.65 else .38
                            for li in face.loop_indices:colors.data[li].color=(shade,shade*.91,shade*.80,1)
                ob.rotation_euler.y=math.copysign(math.pi/2,x);ob.location=(x,0,.43);bpy.context.view_layer.update();L.apply_transform(ob)
            if revision>=4:c.box((w,1.1,.10),(0,0,.5),'wood',.02);c.beam((-1.17,0,.43),(1.17,0,.43),.065)
            for x in (-.55,.55):c.beam((x,.55,.5),(x,1.5,.63),.065)
        c.awning(w+.30,d+.32,2.58,{'A':'sapphire','B':'terracotta','C':'slate'}[shape],shape=='C')
        goods({'A':'apples','B':'bread','C':'fish'}[shape],(-w*.23,-.25 if revision>=3 else 0,1.01))
        goods('jars',(w*.28,.10,1.01))
        hull((w,1.15,1),(0,0,.5));metadata['awning_wind']={'uv2':True,'max_weight':.12}
    elif kind=='goods':goods(p['shape']);hull((.7,.55,.55),(0,0,.275))
    else:raise ValueError(kind)
    ob=c.joined(spec['id']+'__lod0')
    if kind=='driftwood':
        v=L.verts(ob.data);v[:,2]-=v[:,2].min();L.set_verts(ob.data,v)
    if not hulls:
        mn,mx=L.verts(ob.data).min(axis=0),L.verts(ob.data).max(axis=0);hull(mx-mn,(mx+mn)/2)
    col=L.join(hulls,spec['id']+'__collider')
    return ob,col,metadata
